services:
  backend:
    build:
      context: ./backend
      target: prod
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - 4010:4000
    env_file: ./backend/.env
  db:
    image: postgres
    ports:
      - 5433:5432 # local:container
    volumes:
      - /var/lib/postgresql/data
    env_file: ./backend/.env
  frontend:
    build:
      context: ./frontend
      target: prod
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - 3010:3000 # local:container