services:
  backend:
    build: 
      context: ./backend
      target: dev
    container_name: tgc_backend
    ports:
      - 4010:4000
    volumes:
      - ./backend/src/:/app/src/
    env_file: ./backend/.env
  db:
    image: postgres
    ports:
      - 5433:5432
    env_file: ./backend/.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  frontend:
    build: 
      context: ./frontend
      target: dev
    container_name: tgc_frontend
    ports:
      - 3010:3000
    volumes:
      - ./frontend/src/:/app/src/
volumes:
  postgres_volume:
