

GET http://localhost:5001/categories

###

GET http://localhost:5001/categories/10
###

POST http://localhost:5001/categories
content-type: application/json

{
  "name": "New category"
}

###

PATCH http://localhost:5001/categories/10
content-type: application/json

{
  "name": "Update name category"
}

###

DELETE http://localhost:5001/categories/10
