

GET http://localhost:5001/tags

###

GET http://localhost:5001/tags/1
###

POST http://localhost:5001/tags
content-type: application/json

{
  "name": "New tag"
}

###

PATCH http://localhost:5001/tags/5
content-type: application/json

{
  "name": "Update name tag"
}

###

DELETE http://localhost:5001/tags/5
